# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xa3\x02\n\x0fTelemetryRecord\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tdevice_ip\x18\x02 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x03 \x01(\x03\x12\x13\n\x0bmetric_type\x18\x04 \x01(\t\x12\x14\n\x0cmetric_value\x18\x05 \x01(\x01\x12\x0c\n\x04unit\x18\x06 \x01(\t\x12\x16\n\x0einterface_name\x18\x07 \x01(\t\x12\x17\n\x0finterface_index\x18\x08 \x01(\x05\x12\x36\n\x06labels\x18\t \x03(\x0b\x32&.telemetry.TelemetryRecord.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"S\n\x0eTelemetryBatch\x12+\n\x07records\x18\x01 \x03(\x0b\x32\x1a.telemetry.TelemetryRecord\x12\x14\n\x0c\x63ollector_id\x18\x02 \x01(\t\"W\n\x1aSendTelemetryBatchResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x16\n\x0erecords_stored\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2l\n\x12TelemetryIngestion\x12V\n\x12SendTelemetryBatch\x12\x19.telemetry.TelemetryBatch\x1a%.telemetry.SendTelemetryBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYRECORD_LABELSENTRY']._loaded_options = None
  _globals['_TELEMETRYRECORD_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYRECORD']._serialized_start=31
  _globals['_TELEMETRYRECORD']._serialized_end=322
  _globals['_TELEMETRYRECORD_LABELSENTRY']._serialized_start=277
  _globals['_TELEMETRYRECORD_LABELSENTRY']._serialized_end=322
  _globals['_TELEMETRYBATCH']._serialized_start=324
  _globals['_TELEMETRYBATCH']._serialized_end=407
  _globals['_SENDTELEMETRYBATCHRESPONSE']._serialized_start=409
  _globals['_SENDTELEMETRYBATCHRESPONSE']._serialized_end=496
  _globals['_TELEMETRYINGESTION']._serialized_start=498
  _globals['_TELEMETRYINGESTION']._serialized_end=606
# @@protoc_insertion_point(module_scope)
